Auth
paulhulbert/swen344a pull request #3
Opened 2019-02-23 21:00 UTC by paulhulbert

Redirects to Twitter OAuth when the user isn't signed in.

2019-02-23 23:05 UTC, btarr requested changes
looking pretty good just some things that need slight updating

2019-02-23 23:05 UTC, btarr commented on src/utils/index.js
> +export { firebase, auth };
having an `index.js` seems kinda like an antipattern in utils, we should just import the util files separately instead of conglomerating them here.

2019-02-23 23:05 UTC, btarr commented on src/utils/firebase.js
> +const app = firebase.initializeApp({
👍 like this but we should probably have a config file or something if possible

2019-02-23 23:05 UTC, btarr commented on src/utils/firebase.js
> +//import 'firebase/database';
remove this if we're not using it for now

2019-02-23 23:05 UTC, btarr commented on src/utils/withAuth.js
> +                    console.info('Must be authenticated');
is this important to debugging? I want to avoid unnecessary console logs if possible

2019-02-23 23:05 UTC, btarr commented on src/utils/withAuth.js
> +                if (user) {
we should split out this arrow function into another function in the class

2019-02-23 23:05 UTC, btarr commented on src/utils/withAuth.js
> +            auth.getAuth().onAuthStateChanged(user => {
I like this but we should make sure to remove the `onAuthStateChanged` listener in `componentWillUnmount`

2019-02-23 23:05 UTC, btarr commented on src/utils/withAuth.js
> +            auth.getAuth().onAuthStateChanged(user => {
this is a good guide on it: https://stackoverflow.com/questions/37370224/firebase-stop-listening-onauthstatechanged

basically you'll want to change this line to be `this.unsubscribeFromChanges = auth.getAuth...`, then make a `componentWillUnmount` func with this logic:
```
const unsubscribeFromChanges = this.unsubscribeFromChanges;
if (unsubscribeFromChanges) {
  unsubscribeFromChanges();
}
```

or if you prefer the ol one line code golf:
```
this.unsubscribeFromChanges && this.unsubscribeFromChanges();
```

2019-02-23 23:05 UTC, btarr commented on src/utils/withAuth.js
> +                <Delay wait={250}>
What is this for? if we're waiting on something to load we can use [react suspense](https://medium.com/crowdbotics/react-suspense-with-the-fetch-api-3a75c223409d)

2019-02-23 23:05 UTC, btarr commented on src/utils/withAuth.js
> +                    firebase.auth().signInWithRedirect(auth.twitterOAuth());
seems like a pain to force them to login without warning just cause they weren't auth'd. Maybe we should add a `/login` route and redirect there if they're not logged in

2019-02-24 19:34 UTC, btarr commented on src/utils/firebase.js
> +import 'firebase/auth';
we actually don't need this either since we're not using `auth` in this file

2019-02-24 22:22 UTC, paulhulbert commented on src/utils/withAuth.js
> +                <Delay wait={250}>
Honestly, I have no idea what it does.  It was in the firebase auth tutorial.  I was hoping you'd have some idea of what it was.  I can just pull it if you don't.

2019-02-24 22:24 UTC, paulhulbert commented on src/utils/withAuth.js
> +                    firebase.auth().signInWithRedirect(auth.twitterOAuth());
In this PR or should that just be a quality of life thing later?

2019-02-24 22:37 UTC, btarr commented on src/utils/withAuth.js
> +                    firebase.auth().signInWithRedirect(auth.twitterOAuth());
meh we can get this PR through and do that later, just make an issue for it if you can

2019-02-24 22:38 UTC, btarr commented on src/utils/withAuth.js
> +                <Delay wait={250}>
it seems to delay the page load, if it works I'm fine merging it now and looking into ways to improve once it's in

2019-03-02 17:13 UTC, btarr approved these changes

2019-03-02 17:13 UTC, merged